### PR TITLE
Merging 4.0 back into main

### PR DESCRIPTION
**Pull request by MikeAlhayek**

### CODE REVIEW

**Comment by sebastienros** [comment]
Release branch merges should not be squashed. Just regular merge commit.

**Comment by MikeAlhayek** [comment]
I'll make sure we do that for next time.

**Comment by sebastienros** [comment]
I will see if I can fix it. Shouldn't have any impact.

**Comment by sebastienros** [comment]
All done, you might have to pull the repos again since I force pushed 4.0 and 5.0 tags/branches

**Comment by MikeAlhayek** [comment]
Thank you!

**Pull request merged**
