### PR TITLE
Added signed packages

### PR DESCRIPTION
**Pull request by wedge206**

### CODE REVIEW

**Comment by wedge206** [comment]
#175

**Comment by wedge206** [comment]
I'm not sure if any scripts need to be updated to get these to build and push to nuget.

**Comment by sebastienros** [comment]
I'd rather ship only a single version that is strong named. Also pointed here: https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/strong-naming

**Comment by wedge206** [comment]
Interesting.  Releasing two packages (strong named, and not strong named) is such a common practice, I didn't realize it was against the official guidelines.
I'll update this PR.

**Comment by sebastienros** [comment]
I also do a single package for Jint and Esprima. It has always worked for me.

Thanks

**Comment by wedge206** [comment]
Updated

**Comment by sebastienros** [comment]
I didn't understand why I was still seeing all previous commits in the PR, and thought squashing would resolve it. You actually targeted master and didn't realize. I canceled the build and force-pushed to revert the commit. I will try to re-apply it on dev.

**Comment by wedge206** [comment]
Yeah, I noticed when I got the “merged to master” notification

**Pull request merged**
