### PR TITLE
Fixed parameter order of InnerJoin interface

### PR DESCRIPTION
**Pull request by douwinga**
Fix for #477 

I went with the non-breaking change way to fix this, but the parameter order seems odd now.

### CODE REVIEW

**Comment by hishamco** [comment]
I think we need to change the implementation not the interface

**Comment by douwinga** [comment]
I agree, I just wasn't sure if that was a good idea since anybody using this will have queries failing after updating. There wouldn't be any indication as to what changed and that they need to flip the parameters. However, if somebody else is using this, you would expect they would have ran into the same problem I did and have reported it. So it is probably a non issue.

**Comment by hishamco** [comment]
> There wouldn't be any indication as to what changed and that they need to flip the parameters.

You are right, but may be we could log it into the release notes

**Comment by sebastienros** [comment]
Please fix the implementation, users should be using the interface anyway.

**Comment by douwinga** [comment]
It looks like I did fix the implementation with the commits from 7 months ago

**Review by sebastienros — APPROVED** [review]

**Pull request merged**
