### PR TITLE
Transition to netcore rc2 and using dotnet cli

### PR DESCRIPTION
**Pull request by alexbocharov**
@sebastienros 
Using dotnet cli for building. Transition to netstandard. Update dependencies. (In preparation for the transition of the Orchard 2 to netcore rc2)

### CODE REVIEW

**Comment by alexbocharov** [comment]
I have updated the build scripts. You may need to revise the script integration with appveyor.

**Comment by alexbocharov** [comment]
I will fix it

**Comment by sebastienros** [comment]
Let me know how it goes, great effort here.

**Comment by alexbocharov** [comment]
> Let me know how it goes, great effort here.

You mean Orchard2?

**Comment by sebastienros** [comment]
I meant yessql, Orchard2 is even greater!

**Comment by sebastienros** [comment]
Mind joining the gitter room for Orchard2 to let us know the status?

**Comment by alexbocharov** [comment]
I haven't changed anything in functionality for YesSql. Just move on netstandard and coreclr rc2. The main work on the Orchard 2.

**Pull request merged**
