### PR TITLE
Update sql providers packages

### PR DESCRIPTION
**Pull request by agriffard**
https://www.nuget.org/packages/Microsoft.Data.SqlClient/5.0.0
https://www.nuget.org/packages/Microsoft.Data.Sqlite/6.0.7
https://www.nuget.org/packages/MySqlConnector/2.1.11
https://www.nuget.org/packages/Npgsql/6.0.6
https://github.com/npgsql/npgsql/releases/tag/v6.0.6

### CODE REVIEW

**Comment by agriffard** [comment]
Error Message on tests:
```
Microsoft.Data.SqlClient.SqlException : A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: TCP Provider, error: 35 - An internal exception was caught)
---- System.Security.Authentication.AuthenticationException : The remote certificate was rejected by the provided RemoteCertificateValidationCallback.
```

Warning:
`.NET 5.0 is no longer supported and will not receive security updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the .NET support policy.`

**Comment by deanmarcussen** [comment]
You will have to update the connection string to include ‘Encrypt=False’ on the tests.

I think it’s been long enough Seb we should take this.

I had to change any dev strings when we upgraded but all the azure prod connections were fine

**Comment by agriffard** [comment]
`Encrypt=False` works locally but not in build.

**Comment by agriffard** [comment]
Packages updated but exception still occurring in SQL tests.

**Pull request closed without merging**
