### PR TITLE
Adding null var unit test

### LINKED ISSUE #298: Query on column == (variable with null value) doesn't yield results while it should - the sequel
When I perform the following query:

```csharp
var authorName = default(string);
var ps = session.Query<BlogPost, BlogPostByAuthor>().Where(x => x.Author == authorName).ListAsync().Result;
```

0 results are returned, even if there are actually blog posts where Author = NULL.

HOWEVER, as was fixed as part of #89, the following works fine:

```csharp
var ps = session.Query<BlogPost, BlogPostByAuthor>().Where(x => x.Author == null).ListAsync().Result;
```

Notice that it works when I use a literal `null` value when performing the query (one result is returned), but not when I supply a variable with a null value.

Repro steps:

```csharp
// creating a blog post with a null author

var author = default(string);

var post = new BlogPost
{
    Title = "Hello YesSql",
    Author = author,
    Content = "Hello",
    PublishedUtc = DateTime.UtcNow,
};

// saving the post to the database
using (var session = store.CreateSession())
{
    session.Save(post);
}

// loading blog posts by author
using (var session = store.CreateSession())
{
    // This yields 1 result:
    //var ps = await session.Query<BlogPost, BlogPostByAuthor>().Where(x => x.Author == null).ListAsync();

    // But this doesn't:
    var ps = await session.Query<BlogPost, BlogPostByAuthor>().Where(x => x.Author == author).ListAsync();

    Debug.Assert(ps.Any()); // Fails -> there are 0 results
}
```

### PR DESCRIPTION
**Pull request by sebastienros**
Fixes #298

### CODE REVIEW

**Comment by sebastienros** [comment]
@sfmskywalker the issue with that fix is that we should not mix null/non-null string parameters in a "compile query". We have a few of them in OC and we should ensure we are not accepting null values.

**Comment by sebastienros** [comment]
New update, I was able to create a compiled query cache based on what values are null in the compiled query state. Which means there are as many cached queries as potential nullable properties.

**Comment by sebastienros** [comment]
This is the sql output for the compiled query tests:

```
DEBUG: SELECT count(distinct [tpDocument].[Id]) FROM [tpDocument] INNER JOIN [tpPersonByAge] AS [PersonByAge_a1] ON [PersonByAge_a1].[DocumentId] = [tpDocument].[Id] WHERE (([PersonByAge_a1].[Age] = @p0) or ([PersonByAge_a1].[Name] IS NULL))
DEBUG: SELECT count(distinct [tpDocument].[Id]) FROM [tpDocument] INNER JOIN [tpPersonByAge] AS [PersonByAge_a1] ON [PersonByAge_a1].[DocumentId] = [tpDocument].[Id] WHERE (([PersonByAge_a1].[Age] = @p0) or ([PersonByAge_a1].[Name] IS NULL))
DEBUG: SELECT count(distinct [tpDocument].[Id]) FROM [tpDocument] INNER JOIN [tpPersonByAge] AS [PersonByAge_a1] ON [PersonByAge_a1].[DocumentId] = [tpDocument].[Id] WHERE (([PersonByAge_a1].[Age] = @p0) or ([PersonByAge_a1].[Name] IS NULL))
DEBUG: SELECT count(distinct [tpDocument].[Id]) FROM [tpDocument] INNER JOIN [tpPersonByAge] AS [PersonByAge_a1] ON [PersonByAge_a1].[DocumentId] = [tpDocument].[Id] WHERE (([PersonByAge_a1].[Age] = @p0) or ([PersonByAge_a1].[Name] = @p1))
DEBUG: SELECT count(distinct [tpDocument].[Id]) FROM [tpDocument] INNER JOIN [tpPersonByAge] AS [PersonByAge_a1] ON [PersonByAge_a1].[DocumentId] = [tpDocument].[Id] WHERE (([PersonByAge_a1].[Age] = @p0) or ([PersonByAge_a1].[Name] = @p1))
DEBUG: SELECT count(distinct [tpDocument].[Id]) FROM [tpDocument] INNER JOIN [tpPersonByAge] AS [PersonByAge_a1] ON [PersonByAge_a1].[DocumentId] = [tpDocument].[Id] WHERE (([PersonByAge_a1].[Age] = @p0) or ([PersonByAge_a1].[Name] = @p1))
DEBUG: SELECT count(distinct [tpDocument].[Id]) FROM [tpDocument] INNER JOIN [tpPersonByAge] AS [PersonByAge_a1] ON [PersonByAge_a1].[DocumentId] = [tpDocument].[Id] WHERE (([PersonByAge_a1].[Age] = @p0) or ([PersonByAge_a1].[Name] = @p1))
DEBUG: SELECT DISTINCT [tpDocument].* FROM [tpDocument] INNER JOIN [tpPersonByAge] AS [PersonByAge_a1] ON [PersonByAge_a1].[DocumentId] = [tpDocument].[Id] WHERE (([PersonByAge_a1].[Age] = @p0) or ([PersonByAge_a1].[Name] IS NULL))
DEBUG: SELECT DISTINCT [tpDocument].* FROM [tpDocument] INNER JOIN [tpPersonByAge] AS [PersonByAge_a1] ON [PersonByAge_a1].[DocumentId] = [tpDocument].[Id] WHERE (([PersonByAge_a1].[Age] = @p0) or ([PersonByAge_a1].[Name] IS NULL))
DEBUG: SELECT DISTINCT [tpDocument].* FROM [tpDocument] INNER JOIN [tpPersonByAge] AS [PersonByAge_a1] ON [PersonByAge_a1].[DocumentId] = [tpDocument].[Id] WHERE (([PersonByAge_a1].[Age] = @p0) or ([PersonByAge_a1].[Name] IS NULL))
DEBUG: SELECT [tpDocument].* FROM [tpDocument] INNER JOIN [tpPersonByAge] AS [PersonByAge_a1] ON [PersonByAge_a1].[DocumentId] = [tpDocument].[Id] WHERE (([PersonByAge_a1].[Age] = @p0) or ([PersonByAge_a1].[Name] IS NULL)) LIMIT 1
```

Even though it's the same compiled query, the SQL is using "IS NULL" when null is pass as the name.

**Comment by sfmskywalker** [comment]
Awesome 👏🏻

**Pull request merged**
