### PR TITLE
Implements Microsoft.Extensions.Logger

### PR DESCRIPTION
**Pull request by wedge206**
Removes the YesSql.Logger types.
Added UseLogger() Configuration extension.
Replaced LogSql() with LogTrace()

Also updated some dependencies.

### CODE REVIEW

**Comment by wedge206** [comment]
#95

**Comment by sebastienros** [comment]
LGTM

Thanks a lot. IF it's ready let me know and I'll merge it when the tests have passed.

**Comment by wedge206** [comment]
It *should* be working fine.  I haven't tested it with AppInsights yet.  That's my primary use-case, so I should probably make sure it's actually working there before merging.  I'll let you know once I've done some more tests.

**Comment by wedge206** [comment]
@sebastienros Yup.  Confirmed it's working nicely.

**Comment by wedge206** [comment]
A thought I just had is to add the ability to configure which log level SQL statements will be sent at.  I hardcoded it to Trace level.  But it would be easy enough to put the LogSql() method back, and have it send to Trace/Debug/Info/Any level based on configuration.
I'll can add that later if needed.  Just wanted to make a note of it here.

**Comment by sebastienros** [comment]
I think it's good, we just need to configure these namespaces for TRACE if necessary

**Pull request merged**
