### PR TITLE
Oracle dialect and test have been added

### PR DESCRIPTION
**Pull request by mazuryv**
Our team has finished Oracle provider support for YesSql. Could you please review and may be included in future OrchardCore release. Our requirements included both Orchard and Oracle DB, so we didn't have any other way than implement such provider.

### CODE REVIEW

**Comment by sebastienros** [comment]
Acknowledged. I will look at this soon. Thanks for this huge effort!

**Comment by sbiaudet** [comment]
@sebastienros do you plan to include the Oracle provide soon. For a project I need to support Oracle with OrchardCore & Bot Builder. (We've a YesSql Storage for Bot Builder).

**Comment by sebastienros** [comment]
I don't want to maintain the Oracle provider. Every time I built an ORM and had to support it it was a huge pain. However I am ok with including the changes that would allow for having an external one, maintained on another repo, and still released on NuGet.

Can somone open a new PR that only containes the framework changes? That would also refresh these changes has many things have changed in the meantime.

**Comment by Piedone** [comment]
Dialects can now be passed as configuration so this should be possible to do in an independent project, extending YesSql.

**Pull request closed without merging**
