### PR TITLE
Fix alter column issue in Postgres

### LINKED ISSUE #483: The 'modify' keyword is not supported in postgres
I don't understand what this code does. Why compare lengths?

https://github.com/sebastienros/yessql/blob/c0771eb555c67bf419859016cb3563a3540fe7c7/src/YesSql.Provider.PostgreSql/PostgreSqlCommandInterpreter.cs#L18-L22

https://github.com/sebastienros/yessql/issues/244#issuecomment-1489671512

### PR DESCRIPTION
**Pull request by hishamco**
Fixes #483

### CODE REVIEW

**Comment by hishamco** [comment]
While I'm working on this I found two issues:

1- `modify` is incorrect as discussed on the related issue
2- Also, we miss `Type` when we change the column datatype, seems no one alter the column previously in Postgres :)

One more thing that confused me, I'm expecting to not specify the type during the alteration, if we don't the default `bytea` is added to the column which is wrong

**Comment by hishamco** [comment]
Nah, SQLite test is failed!! I presume because it doesn't support alteration if I'm not wrong

**Comment by MikeKry** [comment]
@hishamco 

I would also expect that it is failing because sqlite does not support alter column.. 

Can this be merged? It is vital to have possibility to change column size in postgres.

**Comment by hishamco** [comment]
@sebastienros could you please reply on my [comment](https://github.com/sebastienros/yessql/pull/486#issuecomment-1500723187) so we can finalize this PR?

**Review by sebastienros — APPROVED** [review]

**Comment by hishamco** [comment]
Ready to merge Seb

**Pull request merged**
